import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigator from "@/components/Navigator";
import { Routes } from "@/models/routes.model";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Nextts app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigator paths={[Routes.HOME, Routes.CHARACTERES, Routes.ABOUT]} />
        {children}
      </body>
    </html>
  );
}
